spring:
  profiles:
    active: local
  data:
    mongodb:
      database: members
  security:
    user:
      name: admin
      password: $2a$10$6FqxWBqGqHR2WBVKWu3WpOhR0CZ8Bx0l2eyPfyPGFSYCi4RVg8Sy6
      roles: ADMIN
  jackson:
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      max-file-size: 5MB
server:
  port: 8080
